---
triple:          'x86_64-apple-darwin'
binary-path:     '/Users/samuelknight/Desktop/project1/app'
relocations:
  - { offset: 0x26, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000EA0, symSize: 0xC0 }
  - { offset: 0x41, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100000EA0, symSize: 0xC0 }
...
